class I18N:
    def __init__(self, language):
        if language == "en":
            self.load_text_in_english()
        elif language == "tr":
            self.load_text_in_turkish()
        else:
            raise NotImplementedError("Unsupported language.")

    def load_text_in_english(self):
        self.reservationid_heading = "Reservation ID"
        self.username_heading = "Username"
        self.country_heading = "Country"
        self.city_heading = "City"
        self.numberofpeople_heading = "Number of People"
        self.numberofroom_heading = "Number of Room"
        self.view_heading = "Room View"
        self.breakfast_heading = "Breakfast"
        self.ac_heading = "Air Conditioning"
        self.rs_heading = "Room service"
        self.reservationdate_heading = "Reservation Date"
        self.start_day_heading = "Check-in Day"
        self.finish_day_heading = "Check-out Day"
        self.welcome = "Welcome!"
        self.homepage = "Home Page"
        self.options_main = "Options"
        self.thanks = "Thank You!"
        self.history = "History"
        self.name = "Name:"
        self.surname= "Surname:"
        self.pno = "Phone Number:"
        self.username = "Username:"
        self.password = "Password:"
        self.rpassword = "Password(repeat):"
        self.reservation = "Reservation"
        self.new_reservation = "New Reservation"
        self.reservation_history = "Reservation History"
        self.country = "Country:"
        self.city = "City:"
        self.people = "Number Of People:"
        self.room = "Number Of Room:"
        self.room_type = "Room Type:"
        self.selected_view = "Selected View:"
        self.selected_options = "Selected option(s):"
        self.yes = "Yes"
        self.no = "No"
        self.options = "Options:"
        self.city_view = "City View"
        self.sea_view = "Sea View"
        self.nature_view = "Nature View"
        self.breakfast = "Breakfast"
        self.ac = "Air Conditioning"
        self.rs = "Room Service"
        self.notspecified = "Not Specified"
        self.start_day = "Check-in Day:"
        self.finish_day = "Check-out Day:"
        self.successful = "Your reservation is successful!"
        self.informations = "Your informations are:"
        self.reservationid = "Your reservation id:"
        self.login = "Login"
        self.signup = "Signup"
        self.back = "Back"
        self.signout= "Sign Out"
        self.complete = "Complete Reservation"
        self.elipor = "Welcome to ELIPOR HOTEL reservation system!"
        self.return_homepage = "Return Homepage"
        self.countryList = {'Select': ['Select'],
            'Turkey': ['Select', 'İstanbul', 'Ankara', 'Antalya'],
                        'England': ['Select', 'London', 'Manchester', 'Liverpool'],
                        'Italy': ['Select', 'Venice', 'Rome', 'Milan'],
                        'Netherlands': ['Select', 'Amsterdam', 'Rotterdam', 'Haarlem'],
                        'Spain': ['Select', 'Madrid', 'Barcelona', 'Valencia']}
        self.select = "Select"
        self.home_elipor = "ELIPOR HOTEL"
        self.info1 = "Welcome!"
        self.info2 = "Elipor Hotel has hotels in 5 different countries.\nWhich are; Turkey, England, Italy, Netherlands and Spain!\n" \
                     "You can also select from various cties including Istanbul, Amsterdam, Venice and London!\n" \
                     "\nOur system offers various options for your stay in Elipor Hotel." \
                     "\nYou can easily select if you would like to have breakfast included, or air conditioning option included in your room during your stay!"
        self.info3 = "\nSelect MAKE NEW RESERVATION from the menu above to fill up the form.\nSelect RESERVATION HISTORY button to see your previous reservations."
        self.lang_select_note = "Türkçe için F2'ye basınız."
        self.error = "Error"
        self.name_error = "Name must be entered:\n- at least 2 characters,\n- at most 20 characters must be entered."
        self.surname_error = "Surname must be entered:\n- at least 2 characters,\n- at most 20 characters must be entered."
        self.pNo_error = "Phone number must be entered:\n- at least 9 digits should be eneterd."
        self.username_error = "Username must be entered:\n- at least 5 characters or digits should be eneterd,\n- only . - _ can be used."
        self.password_error = "Password must be entered:\n- at least 7 characters or digits should be eneterd,\n- at least one capital letter,\n" \
                              "- at least one lower case letter and,\n- at least one number must be entered."
        self.price_label = "You can pay your visit while checking out!"
        self.delete = "To erase your reservation: While reservation you want to delete is selected press DEL key."
        self.mismatched = "Username and password mismatched."
        self.password_mismatched = "Passwords are not matching"
        self.username_exist = "Username is already exists in database. Please enter different one."
        self.country_error = "Country must be selected"
        self.city_error = "City must be selected"
        self.no_of_people_error = "Number of people must be selected"
        self.no_of_room_error = "Number of room must be selected"
        self.date_error = "Please select a valid date."
        self.delete_reservation = "Delete Reservation"
        self.are_you_sure = "Your reservation will be canceled. Are you sure?"
        self.are_you_sure_2 = "Are you sure?"

    def load_text_in_turkish(self):
        self.reservationid_heading = "Rezervasyon No"
        self.username_heading = "Kullanıcı Adı"
        self.country_heading = "Ülke"
        self.city_heading = "Şehir"
        self.numberofpeople_heading = "Kişi sayısı"
        self.numberofroom_heading = "Oda Sayısı"
        self.view_heading = "Manzara"
        self.breakfast_heading = "Kahvaltı"
        self.ac_heading = "Havalandırma"
        self.rs_heading = "Oda Servisi"
        self.reservationdate_heading = "Rezervasyon Tarihi"
        self.start_day_heading = "Giriş Tarihi"
        self.finish_day_heading = "Çıkış Tarihi"
        self.welcome = "Hoşgeldiniz!"
        self.homepage = "Ana Sayfa"
        self.options_main = "Seçenekler"
        self.thanks = "Teşekkürler!"
        self.history = "Geçmiş"
        self.name = "İsim:"
        self.surname= "Soyisim:"
        self.pno = "Telefon Numarası:"
        self.username = "Kullanıcı Adı:"
        self.password = "Şifre:"
        self.rpassword = "Şifre(tekrar):"
        self.reservation = "Rezervasyon"
        self.new_reservation = "Yeni Rezervasyon"
        self.reservation_history = "Rezervasyon Geçmişi"
        self.country = "Ülke:"
        self.city = "Şehir:"
        self.people = "Kişi sayısı:"
        self.room = "Oda sayısı:"
        self.room_type = "Manzara Tercihi:"
        self.selected_view = "Seçilen Manzaralar:"
        self.selected_options = "Seçilen Seçenek(ler):"
        self.yes = "Evet"
        self.no = "Hayır"
        self.options = "Seçenekler:"
        self.city_view = "Şehir Manzarası"
        self.sea_view = "Deniz Manzarası"
        self.nature_view = "Doğa Manzarası"
        self.breakfast = "Kahvaltı"
        self.ac = "Havalandırma"
        self.rs = "Oda Servisi"
        self.notspecified = "Tercih Edilmedi"
        self.start_day = "Giriş Günü:"
        self.finish_day = "Çıkış Günü:"
        self.successful = "Rezervasyonunuz başarılı!"
        self.informations = "Bilgileriniz:"
        self.reservationid = "Rezervasyon no:"
        self.login = "Giriş yap"
        self.signup = "Kayıt ol"
        self.elipor = "ELIPOR OTEL rezervasyon sistemine hoşgeldiniz!"
        self.back = "Geri"
        self.signout= "Çıkış yap"
        self.complete = "Rezervasyonu Tamamla"
        self.return_homepage = "Anasayfaya Dön"
        self.countryList = {'Lütfen Seçiniz': ['Lütfen Seçiniz'],
                        'Türkiye': ['Lütfen Seçiniz', 'İstanbul', 'Ankara', 'Antalya'],
                        'İngiltere': ['Lütfen Seçiniz', 'Londra', 'Manchester', 'Liverpool'],
                        'İtalya': ['Lütfen Seçiniz', 'Venedik', 'Roma', 'Milano'],
                        'Hollanda': ['Lütfen Seçiniz', 'Amsterdam', 'Rotterdam', 'Haarlem'],
                        'İspanya': ['Lütfen Seçiniz', 'Madrid', 'Barselona', 'Valensiya']}
        self.select = "Lütfen seçiniz"
        self.home_elipor = "ELİPOR OTEL"
        self.info1 = "Hoşgeldiniz!"
        self.info2 = "Elipor Otel'in Türkiye, İngiltere, İtalya, Hollanda ve İspanya olmak üzere 5 farklı ülkede şubesi vardır.\n" \
                     "İstanbul, Amsterdam, Venedik ve Londra başta olmak üzere şehir seçeneklerimiz bulunmaktadır!\n" \
                     "\nSistemimiz, size Elipor Otel'deki konaklamanız için çeşitli seçenekler sunar." \
                     "\nBunların arasından kolaylıkla kahvaltı veya odanızda havalandırma isteyip istemediğinizi seçebilirsiniz."
        self.info3 = "\nYukarıda yer alan menüden YENİ REZERVASYON kısmını seçerek formu doldurabilirsiniz." \
                     "\nREZERVASYON GEÇMİŞİ'ni seçerek geçmiş rezervasyonlarınızı görebilirsiniz."
        self.lang_select_note = "For English press F1."
        self.error = "Hata"
        self.name_error = "Lütfen isminizi giriniz:\n- en az iki karakter,\n- en fazla 20 karakter girilmelidir."
        self.surname_error = "Lütfen soyadınızı giriniz:\n- en az iki karakter,\n- en fazla 20 karakter girilmelidir."
        self.pNo_error = "Lütfen telefon numaranızı giriniz:\n- en az 9 rakam girilmelidir."
        self.username_error = "Lütfen kullanıcı adı giriniz:\n- en az 5 karakter veya rakam girilmelidir,\n- yalnızca . - _ kullanılabilir."
        self.password_error = "Lütfen şifrenizi giriniz:\n- en az 7 karakter veya rakam girilmelidir,\n- en az bir büyük harf,\n" \
                              "- en az bir küçük harf ve\n- en az bir rakam girilmelidir."
        self.price_label = "Ödemenizi otelimizden çıkış yaparken yapabilirsiniz!"
        self.delete = "Rezervasyonu silmek için: Silmek istediğiniz rezervasyon seçili iken DEL tuşuna basınız."
        self.mismatched = "Kullanıcı adı ve şifre eşleşmiyor."
        self.password_mismatched = "Şifreler eşleşmiyor"
        self.username_exist = "Bu kullanıcı adı başka birine ait. Lütfen başka bir kullanıcı adı seçin."
        self.country_error = "Ülke seçilmek zorundadır"
        self.city_error = "Şehir seçilmek zorundadır"
        self.no_of_people_error = "Kişi sayısı seçilmek zorundadır"
        self.no_of_room_error = "Oda sayısı seçilmek zorundadır"
        self.date_error = "Lütfen geçerli bir tarih giriniz."
        self.delete_reservation = "Rezervasyonu Sil"
        self.are_you_sure = "Rezervasyonunuz iptal edilecektir. Devam etmek istiyor musunuz?"
        self.are_you_sure_2 = "Devam etmek istiyor musunuz?"

